CREATE TABLE users(
	id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
	email VARCHAR(255) NOT NULL UNIQUE,
    avatar VARCHAR(255),
    password VARCHAR(255) NOT NULL,
    rol TINYINT DEFAULT 0,
    mailShipping TINYINT DEFAULT 0,
    privateShipping TINYINT DEFAULT 0,
    noShipping TINYINT DEFAULT 0,
    averageScore DECIMAL DEFAULT 0,
	createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP,
    deletedAt DATETIME
);
CREATE TABLE products(
	id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    price DECIMAL NOT NULL,
    size VARCHAR(255),
    quantity INT DEFAULT 1,
    idUser INT UNSIGNED NOT NULL,
	createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP,
    deletedAt DATETIME
);
CREATE TABLE keywords(
	id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
	createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP,
    deletedAt DATETIME
);
CREATE TABLE productkeys(
	id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    idProduct INT UNSIGNED NOT NULL,
    idKeyword INT UNSIGNED NOT NULL,
	createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP,
    deletedAt DATETIME
);
CREATE TABLE productImages(
	id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    filename VARCHAR(255) NOT NULL,
    idProduct INT UNSIGNED NOT NULL,
	createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP,
    deletedAt DATETIME
);
CREATE TABLE adresses(
	id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    idUser INT UNSIGNED NOT NULL,
    street VARCHAR(255) NOT NULL,
    number TINYINT NOT NULL,
    floor INT,
    door INT,
	createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP,
    deletedAt DATETIME
);
ALTER TABLE productImages
ADD FOREIGN KEY(idProduct) REFERENCES products(id);
ALTER TABLE products
ADD FOREIGN KEY(idUser) REFERENCES users(id);
ALTER TABLE productkeys
ADD FOREIGN KEY(idProduct) REFERENCES products(id);
ALTER TABLE productkeys
ADD FOREIGN KEY(idKeyword) REFERENCES keywords(id);
ALTER TABLE adresses
ADD FOREIGN KEY(idUser) REFERENCES users(id);
ALTER TABLE products
ADD COLUMN status tinyint NOT NULL;

